steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'REACT_APP_API_BASE=${_BACKEND_URL}'
      - '-t'
      - 'us-central1-docker.pkg.dev/gtm-cloud-helpdesk/email-composer-repo/email-composer-frontend:v1'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/gtm-cloud-helpdesk/email-composer-repo/email-composer-frontend:v1'
substitutions:
  _BACKEND_URL: ''  # Set after first deploy
